x-volumes:
  &default-volumes
    volumes:
      - .:/app/

services:
  test:
    image: gitlab-registry-production.govcms.amazee.io/govcms/images/ci${GOVCMS_CI_IMAGE_VERSION:-}
    << : *default-volumes
    environment:
      GOVCMS_GITHUB_TOKEN: ${GOVCMS_GITHUB_TOKEN:-}
